version: 0.5.0-{build}
image: Visual Studio 2017
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "Current"

platform:
  - x86
    ffmpeg_url:https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-3.4.1-win32-static.zip
    ffmpeg_ver:3.4.1-win32-static
  - x64
    ffmpeg_url:https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.4.1-win64-static.zip
    ffmpeg_ver:3.4.1-win64-static

#environment:
#  matrix:
#    - nodejs_version: "Current"
#    - platform: "x64"
#    - ffmpeg_url: "https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.4.1-win64-static.zip"
#    - ffmpeg_ver: "3.4.1-wind64-static"

#environment:
  #global:
    #nodejs_version: "Current"
  #matrix:
    #- platform: x64
      #ffmpeg_url: https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.4.1-win64-static.zip
      #ffmpeg_ver: 3.4.1-win64-static
        #- nodejs_version: 8
        #- nodejs_version: Current
    #- platform: x86
      #ffmpeg_url: https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-3.4.1-win32-static.zip
      #ffmpeg_ver: 3.4.1-win32-static
        #- nodejs_version: 8
        #- nodejs_version: Current

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - ps: Start-FileDownload $env:ffmpeg_url
  - 7z x ffmpeg-%ffmpeg_ver%.zip
  - PATH=%PATH%;%cd%\ffmpeg-%ffmpeg_ver%\bin
  - ffmpeg -version
  - SET

test_script:
  - node --version
  - npm --version
  - npm test

build: off