version: 0.5.0-{build}
image: Visual Studio 2017

environment:
  matrix:
    - platform: x64
      nodejs_version: 8
    - platform: x64
      nodejs_version: Current
    - platform: x86
      nodejs_version: 8
    - platform: x86
      nodejs_version: Current

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off