image:
- Ubuntu
- Visual Studio 2017
environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10
platform:
  - x86
  - x64
cache:
  - node_modules
install:
  - cmd: powershell Install-Product node $env:nodejs_version $env:platform
  - sh: nvm install $nodejs_version
  - npm install
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER"
test_script:
  - node --version
  - npm --version
  - npm test
build: off